import { GetStaticProps, NextPage } from "next";
import { createProxySSGHelpers } from "@trpc/react/ssg";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { appRouter } from "../server/trpc/router";
import superjson from "superjson";
import Link from "next/link";
import { createContext } from "../server/trpc/context";

export const getStaticProps: GetStaticProps = async () => {
  const ssg = createProxySSGHelpers({
    router: appRouter,
    ctx: await createContext(),
    transformer: superjson,
  });

  await ssg.post.all.fetch();

  return {
    props: {
      trpcState: ssg.dehydrate(),
    },
    revalidate: 60,
  };
};

const Home: NextPage = () => {
  const allPosts = trpc.post.all.useQuery();

  return (
    <>
      <Head>
        <title>Ed Allonby</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Ed Allonby
        </h1>
        <div>
          {allPosts.data?.map((blogPost) => (
            <Link key={blogPost.slug} href={`posts/${blogPost.slug}`}>
              <a className="hover:underline">{blogPost.title}</a>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
