import { createSSGHelpers } from "@trpc/react/ssg";
import { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { appRouter } from "../server/router";
import superjson from "superjson";
import Link from "next/link";

export async function getStaticProps() {
  const ssg = createSSGHelpers({
    router: appRouter,
    ctx: {},
    transformer: superjson,
  });

  await ssg.fetchQuery("post.all");

  return {
    props: {
      trpcState: ssg.dehydrate(),
    },
    revalidate: 1,
  };
}

const Home: NextPage = () => {
  const postQuery = trpc.useQuery(["post.all"], { staleTime: 3600 });
  return (
    <>
      <Head>
        <title>Ed Allonby</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Ed Allonby
        </h1>
        <div>
          {postQuery.data?.map((blogPost) => (
            <Link key={blogPost.slug} href={`posts/${blogPost.slug}`}>
              <a className="hover:underline">{blogPost.title}</a>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
